ALTER TABLE EXI_023664.ADDRESS ADD 
CONSTRAINT ADDRESS_PK
 FOREIGN KEY (ADDRESS_ID)
 REFERENCES EXI_023664.SALES (SALES_ID)
 ENABLE
 VALIDATE;

ALTER TABLE EXI_023664.ORDERS_ID ADD 
CONSTRAINT CITIES_PK
 PRIMARY KEY (ORDER_ID)
 ENABLE
 VALIDATE;

CREATE TABLE EXI_023664.SHIPPING
(
  Ship_method  VARCHAR2(1),
  Shipping     VARCHAR2(1),
  Tax          VARCHAR2(1),
  Shipping_ID  NUMBER
);


CREATE TABLE EXI_023664.CUSTOMERS
(
  FIRST_NAME VARCHAR2(1),
  LAST_NAME     VARCHAR2(1),
  EMAIL_ADDRESS          VARCHAR2(1),
  CUSTOMER_ID  NUMBER,
COMPANY_NAME VARCHAR2(1)

);
CREATE TABLE EXI_023664.Culture
(
  Culture_ID           NUMBER,
  Culture_Description  VARCHAR2(1)
);


ALTER TABLE EXI_023664.Culture ADD (
  CONSTRAINT Culture_PK
  PRIMARY KEY
  (Culture_ID)
  ENABLE VALIDATE);


ALTER TABLE EXI_023664.SHIPPING ADD (
  CONSTRAINT SHIPPING_PK
  PRIMARY KEY
  (Shipping_ID)
  ENABLE VALIDATE);

ALTER TABLE EXI_023664.CITIES ADD 
CONSTRAINT ORDERS_ID_PK
 PRIMARY KEY (CITY_ID)
 ENABLE
 VALIDATE;

ALTER TABLE EXI_023664.ORDERS_ID ADD 
CONSTRAINT CUSTOMERS_PK
 PRIMARY KEY (ORDER_ID)
 ENABLE
 VALIDATE;

ALTER TABLE EXI_023664.SALES ADD 
CONSTRAINT SALES_PK
 PRIMARY KEY (SALES_ID)
 ENABLE
 VALIDATE;

ALTER TABLE EXI_023664.SALES ADD 
CONSTRAINT PRODUCTS_PK
 PRIMARY KEY (SALES_ID)
 ENABLE
 VALIDATE;

ALTER TABLE EXI_023664.SALES ADD 
CONSTRAINT SALES_PK
 PRIMARY KEY (PRODUCT_NAME, SALES_ID)
 ENABLE
 VALIDATE;

ALTER TABLE EXI_023664.PRODUCTS ADD 
CONSTRAINT SALES_PK
 PRIMARY KEY (PRODUCT_ID)
 ENABLE
 VALIDATE;

ALTER TABLE EXI_023664.ORDERS_ID ADD 
CONSTRAINT ORDERS_ID_PK
 PRIMARY KEY (ORDER_ID)
 ENABLE
 VALIDATE;

CREATE SEQUENCE EXI_023664.ORDERS
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE EXI_023664.CUSTOMERS1
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE EXI_023664.SALES1
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE EXI_023664.PRODUCTS1
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE EXI_023664.CITIES
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE EXI_023664.ADDRESS1
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

